# THIS FILE IS AUTOGENERATED, DON'T EDIT!

import pytest


@pytest.fixture(scope='session')
def sql_files() -> set:
    return set([
        # Generated from cleanup_expired_links.sql
        "cleanup_expired_links",
    
        # Generated from delete_code.sql
        "delete_code",
    
        # Generated from get_code_info.sql
        "get_code_info",
    
        # Generated from insert_link.sql
        "insert_link",
    
        # Generated from is_code_available.sql
        "is_code_available",
    
        # Generated from redirect.sql
        "redirect",
    ])
