#pragma once

/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <userver/storages/query.hpp>

namespace link_storage_queries::sql {


// Generated from cleanup_expired_links.sql
extern const USERVER_NAMESPACE::storages::Query kCleanupExpiredLinks;


// Generated from delete_code.sql
extern const USERVER_NAMESPACE::storages::Query kDeleteCode;


// Generated from get_code_info.sql
extern const USERVER_NAMESPACE::storages::Query kGetCodeInfo;


// Generated from insert_link.sql
extern const USERVER_NAMESPACE::storages::Query kInsertLink;


// Generated from is_code_available.sql
extern const USERVER_NAMESPACE::storages::Query kIsCodeAvailable;


// Generated from redirect.sql
extern const USERVER_NAMESPACE::storages::Query kRedirect;

}  // namespace link_storage_queries::sql
